services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py init_tasks &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "

  celery_worker:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev

  celery_beat:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev

  frontend:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:5173"
      