# Generated by Django 5.2.1 on 2025-07-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='felog',
            options={'verbose_name': 'Frontend Log', 'verbose_name_plural': 'Frontend Logs'},
        ),
    ]
