# Generated by Django 5.2.1 on 2025-08-13 23:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModerationAnnotation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModerationEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'Unpublish')])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSnapshot',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'Unpublish')], default=1)),
                ('title', models.CharField(db_index=True, max_length=60)),
                ('summary', models.TextField(blank=True, default='', max_length=500)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_created_b5cc75_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_status_edb746_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='article',
            name='last_moderation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Rejected'), (4, 'Unpublished')], db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'published_at'], name='articles_ar_author__b81173_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'created_at'], name='articles_ar_status_cbb22b_idx'),
        ),
        migrations.AddField(
            model_name='articlemoderationannotation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_annotations_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlemoderationevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_moderation_events_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlemoderationevent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_moderation_events', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlesnapshot',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_snapshots', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlesnapshot',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_snapshots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlemoderationevent',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_moderation_events', to='articles.articlesnapshot'),
        ),
        migrations.AddField(
            model_name='articlemoderationannotation',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_annotations', to='articles.articlesnapshot'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['article', 'created_at'], name='articles_ar_article_7adca5_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['article', 'type', 'created_at'], name='articles_ar_article_3d2291_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['article', 'content_hash'], name='articles_ar_article_da3316_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationevent',
            index=models.Index(fields=['article', 'created_at'], name='articles_ar_article_9c3a38_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationevent',
            index=models.Index(fields=['actor', 'created_at'], name='articles_ar_actor_i_55f40b_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationevent',
            index=models.Index(fields=['snapshot', 'created_at'], name='articles_ar_snapsho_3a707d_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationevent',
            index=models.Index(fields=['type', 'created_at'], name='articles_ar_type_c347af_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationannotation',
            index=models.Index(fields=['snapshot', 'created_at'], name='articles_ar_snapsho_a2c846_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationannotation',
            index=models.Index(fields=['author', 'created_at'], name='articles_ar_author__9672c3_idx'),
        ),
    ]
