# Generated by Django 5.2.1 on 2025-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlemoderationannotation_articlemoderationevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_json',
        ),
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='content_json',
        ),
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='articlesnapshot',
            name='content_md',
            field=models.TextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
    ]
