# Generated by Django 5.2.1 on 2025-09-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_content_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='content_html',
        ),
    ]
