# Generated by Django 5.2.1 on 2025-09-12 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_content_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='', max_length=60)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('content_md', models.TextField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_published_version', to='articles.article')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
