# Generated by Django 5.2.1 on 2025-09-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemoderationannotation',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='articlemoderationannotation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articlemoderationevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='updated_at',
        ),
    ]
