# Generated by Django 5.2.1 on 2025-09-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_articlemoderationannotation_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articlemoderationannotation',
            name='articles_ar_snapsho_a2c846_idx',
        ),
        migrations.RemoveIndex(
            model_name='articlemoderationannotation',
            name='articles_ar_author__9672c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='articlesnapshot',
            name='articles_ar_article_3d2291_idx',
        ),
        migrations.RemoveField(
            model_name='articlemoderationannotation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articlemoderationannotation',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='articlemoderationannotation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='type',
        ),
        migrations.AddField(
            model_name='articlemoderationannotation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_annotations', to='articles.articlemoderationevent'),
        ),
        migrations.AlterField(
            model_name='articlemoderationevent',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_moderation_events', to='articles.articlesnapshot'),
        ),
        migrations.AddIndex(
            model_name='articlemoderationannotation',
            index=models.Index(fields=['event', 'created_at'], name='articles_ar_event_i_d73f51_idx'),
        ),
    ]
