# Generated by Django 5.2.1 on 2025-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articlemoderationannotation_articles_ar_snapsho_a2c846_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemoderationevent',
            name='annotation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleModerationAnnotation',
        ),
    ]
