# Generated by Django 5.2.1 on 2025-09-13 02:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlemoderationevent_annotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.CreateModel(
            name='SourceArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(db_index=True, default='', max_length=60)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('content_md', models.TextField(blank=True, default=dict)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Rejected'), (4, 'Unpublished'), (5, 'Deleted')], db_index=True, default=0)),
                ('last_moderation_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='articlemoderationevent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_moderation_events', to='articles.sourcearticle'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_snapshots', to='articles.sourcearticle'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_published_version', to='articles.sourcearticle'),
        ),
        migrations.AddIndex(
            model_name='sourcearticle',
            index=models.Index(fields=['author', 'created_at'], name='articles_so_author__7d3dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcearticle',
            index=models.Index(fields=['status', 'created_at'], name='articles_so_status_044214_idx'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
