# Generated by Django 5.2.1 on 2025-09-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_author_sourcearticle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesnapshot',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='sourcearticle',
            name='summary',
        ),
    ]
