# Generated by Django 5.2.1 on 2025-09-13 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_articlesnapshot_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articlemoderationevent',
            name='articles_ar_actor_i_55f40b_idx',
        ),
        migrations.RenameField(
            model_name='articlemoderationevent',
            old_name='actor',
            new_name='moderator',
        ),
        migrations.AddIndex(
            model_name='articlemoderationevent',
            index=models.Index(fields=['moderator', 'created_at'], name='articles_ar_moderat_1ccf15_idx'),
        ),
    ]
