# Generated by Django 5.2.1 on 2025-12-19 01:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_articlemoderationevent_articles_ar_actor_i_55f40b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedarticle',
            name='content_md',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='content_md',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Submit'), (2, 'Approve'), (3, 'Reject'), (4, 'Unpublish')])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events_actors', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_events', to='articles.sourcearticle')),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='articles.articlesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ArticleModerationEvent',
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['article', 'created_at'], name='articles_ar_article_80f5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['actor', 'created_at'], name='articles_ar_actor_i_7fd01f_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['snapshot', 'created_at'], name='articles_ar_snapsho_fa47b2_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['type', 'created_at'], name='articles_ar_type_d32c5d_idx'),
        ),
    ]
