# Generated by Django 5.2.1 on 2025-12-19 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_publishedarticle_content_md_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleevent',
            name='articles_ar_type_d32c5d_idx',
        ),
        migrations.RenameField(
            model_name='articleevent',
            old_name='type',
            new_name='event_type',
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['event_type', 'created_at'], name='articles_ar_event_t_b530f1_idx'),
        ),
    ]
