# Generated by Django 5.2.1 on 2025-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_articleevent_articles_ar_type_d32c5d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Submit'), (2, 'Approve'), (3, 'Reject'), (4, 'Unpublish'), (5, 'Delete')]),
        ),
    ]
