# Generated by Django 5.2.1 on 2025-12-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_articleevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_published_version', to='articles.sourcearticle'),
        ),
    ]
