# Generated by Django 5.2.1 on 2025-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_publishedarticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Submit'), (2, 'Withdraw'), (3, 'Approve'), (4, 'Reject'), (5, 'Unpublish'), (6, 'Delete')]),
        ),
    ]
