# Generated by Django 5.2.1 on 2025-12-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_articleevent_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesnapshot',
            old_name='content_md',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='publishedarticle',
            old_name='content_md',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sourcearticle',
            old_name='content_md',
            new_name='content',
        ),
    ]
