# Generated by Django 5.2.1 on 2025-12-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_rename_content_md_articlesnapshot_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesnapshot',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='content',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='content',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
