# Generated by Django 5.2.1 on 2025-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_publishedarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='publishedarticle',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='publishedarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
