# Generated by Django 5.2.1 on 2025-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_publishedarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesnapshot',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
